# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c40e9bf32cdfca39cf27e28fb2374707db485c6d98800930d07d9a56075732ad4e49b4a71c15a650fcd23070715d1a9230b19cfb073296202d92f9816f376f03

test:
  secret_key_base: 0e4f8bc13c60f7db5a74c21a441588021ce79059b7596b0ab2e14a6f3aa31ff444181c0fedad5ff92fbba62b824f00cd385f4d191a8404983321ffef844612c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
